### ISSUE TITLE
Unable to use plugin

### ISSUE THREAD

**Issue by shrnjad** [paulloz/godot-ink#13]
I managed to read a Godot file some time ago with the older version of the plugin.

However with the new version:

- I can not activate the plugin. When I try to switch the plugin to active, Godot crashes.
- There is no Ink tab in the editor.
- I can not see Ink-files in the resource view. (no .ink and no .json files) Therefore I can also not import them.
- Without the import, I can not set an Ink file in the InkStory node. (I think)

I am on the newest Godot-Mono version 3.1.1.

Can you give me a pointer how I might start using the plugin?

**Comment by shrnjad** [comment]
I fixed the issue by adding the item group to the .csproj file. Sorry for not reading the whole readme before posting! 😃

**Comment by paulloz** [comment]
No problem :wink:
