### ISSUE TITLE
Error when activating plugin for the first time in 3.2

### ISSUE THREAD

**Issue by mcoorlim** [paulloz/godot-ink#15]
When starting a new project, when I go to activate the plugin in 3.2 I get the following error

> Unable to load addon script from path: 'res://addons/paulloz.ink/PaullozDotInk.cs' There seems to be an error in the code, please check the syntax.

**Comment by paulloz** [comment]
Hi, this error should be resolved by going through the [troubleshooting section of the readme](https://github.com/paulloz/godot-ink/blob/master/README.md#troubleshooting).

**Comment by mcoorlim** [comment]
Sorry for asking such a basic question, but where do I find my .csproj file to make the adjustments? Or how do I get godot to generate one?

**Comment by paulloz** [comment]
Don't worry 🙂  
The `.sln` and `.csproj` are generated if they don't exist and you try to build your Godot project with a `.cs` script. They'll then be located in your project's root folder.

**Comment by mcoorlim** [comment]
Thanks - I've only been using gdscript so far, so don't really have experience using C# with godot, and I've only built an ink wrapper in Unity. To confirm, I'd need to have at least one C# script in the project before activating the plugin to give me a .csproj to edit?

**Comment by paulloz** [comment]
Yep, you need to build your project a first time with a C# script in it and then you should be good to go.

**Comment by mcoorlim** [comment]
Still getting the error. I'll try to work around the plugin by attaching InkStory.cs to a node.

**Comment by paulloz** [comment]
I forgot to mention you'll need to build another time the whole project once the `.csproj` has been updated.
