### ISSUE TITLE
Localization support a-la YarnSpinner

### ISSUE THREAD

**Issue by Sekitan** [paulloz/godot-ink#16]
YarnSpinner is used to integrate Yarn files into Unity.  They include this nifty tool for localizing your dialog into other languages: https://www.secretlab.com.au/blog/2016/9/27/yarn-spinner-localisation

To summarize; it locates every line visible to the player and appends a '#Line:line_number' at the end.
Then it exports them all to a .csv with the first column being #Line:line_number, followed by native_language, localized_language_1, etc.
It can then import that .csv and replace the dialog in-game to the preferred language.

Ink offers a lot of features that can make it hard to localize using this method.  However for most users making games featuring basic dialog or simple trees this would be incredibly useful, it would be nice to see as an option.

**Comment by lunarcloud** [comment]
What's wrong with just having story.en.ink and story.ptbr.ink etc?
Is it the localization services that really want a CSV the issue?
Honestly curious.

**Comment by joethephish** [comment]
Yes, localisation services is one problem, though some devs have used exactly the approach you describe.

The elegant thing about the yarn spinner approach is that it means that you can insert new lines and do edits while retaining the original IDs, and know which content has changed. It also means that you have a separation of logic and content, meaning that localised files won’t accidentally go out of sync if the logic changes.

**Comment by lunarcloud** [comment]
Sounds logical, though "which content has changed" seems like a job for git.

I've gone through the pain on simple key-value pair localization (angular json i18n) getting out of sync, so the task is just plain error-prone without vigilance imho. 

But any feature that can make it easier is welcome if it works :)

**Comment by joethephish** [comment]
Yeah I wondered about making use of git to detect changes and to understand a sort of line number independent persistence. But despite the ubiquity of git, maybe it feels like an overly strong dependency? Like, lots of game teams like Perforce for example. But it would certainly be a cleverly elegant approach.

When you say key value persistence, are the keys the original language content, or some ID? (I would prefer not to use the original content since it could depend on context of nearby other content)

In any case, not a small undertaking by any means.

**Comment by paulloz** [comment]
Also, I doubt this should be implemented in an integration package. Looks like an issue for the main ink repo 😅 
Translation is a big issue with ink games for now tho.

**Comment by Sekitan** [comment]
Me again, so I'm trying to implement a simple localization method where I am trying to set and load the story through gdscript.  However I can't get it to work:
`story.InkFile = 'res://Ink/my_story_en.json'
story.LoadStory()`
Doesn't load anything.  Only setting the story through the inspector, checking autoload, and commenting out the two lines above does the story properly load.
If I set it in the inspector and leave these two lines active the story doesn't load either.
Sorry if this is off-topic but what gives?

**Comment by paulloz** [comment]
@Sekitan Hi! It's totally off-topic but no worries 😀 
The issue here is that `.InkFile` should not contain a path to a file but the actual Godot resource object.
```gdscript
story.InkFile = ResourceLoader.load("res://Ink/my_story_en.json")
story.LoadStory()
```

I'm opening an issue to provide better error messages, I think it's something we're lacking here (and was hard to spot when I was the only person using this integration 😅): #18

**Comment by Sekitan** [comment]
Appreciated!

So my basic localization method works like this:
First, have all your .json/.ink files end in `_lanuage.json` for example `_en.json` or `_fr.json`.
So your file path would look something like `res://Ink/my_story_en.json`

Next, instead of typing:
`story.InkFile = ResourceLoader.load("res://Ink/my_story_en.json")`
Do this:
`story.InkFile = ResourceLoader.load( dialog_file + localization)`
`dialog_file` is a string that holds a string of the story name without the end:
`var dialog file = "res://Ink/my_story"`
`localization` is a string that changes according to what language the player selects.
`var localization = "_en.json"` or `var localization = "_fr.json"`, etc.

This setup takes some micromanagement and you need a .json/.ink file per translation but as long as you remember to name and reference the files correctly it will load the right translation automatically.

**Comment by paulloz** [comment]
Nice, you might want to be cautious about changing language mid-story or that kind of things.
If that's OK, I'm going to close this issue because it's not _really_ related to this repository.  
Feel free to continue commenting here if need be.
