### ISSUE TITLE
Error using LoadStory()

### ISSUE THREAD

**Issue by shingle-bells** [paulloz/godot-ink#17]
When I try to load an ink file through GDscript, I get an error.

Here's the offending line:
```
func _ready():
	story.LoadStory("res://data/ink/story1.ink")
```
And here's the error:
```
E 0:00:01:0281   System.String System.String.Substring(Int32 , Int32 ): System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.

Parameter name: length
  <C++ Error>    Unhandled exception
  <C++ Source>   :0 @ System.String System.String.Substring(Int32 , Int32 )()
  <Stack Trace>  :0 @ System.String System.String.Substring(Int32 , Int32 )()
                 :0 @ System.Object Ink.Runtime.SimpleJson+Reader.ReadObject()()
                 :0 @ Ink.Runtime.SimpleJson+Reader..ctor(System.String )()
                 :0 @ System.Collections.Generic.Dictionary`2[System.String,System.Object] Ink.Runtime.SimpleJson.TextToDictionary(System.String )()
                 :0 @ void Ink.Runtime.StoryState.LoadJson(System.String )()
                 InkStory.cs:255 @ void InkStory.SetState(System.String )()
                 InkStory.cs:77 @ Boolean InkStory.LoadStory(System.String )()
```
Any ideas? I have inklecate linked to properly, and if I set the story in the editor it loads fine.

**Comment by shingle-bells** [comment]
Bump

**Comment by lunarcloud** [comment]
have you tried loading the json instead of the raw ink file?

**Comment by shingle-bells** [comment]
That doesn't work either, sadly.

**Comment by shingle-bells** [comment]
Update: I should have mentioned, but loading the JSON yields the exact same error

**Comment by paulloz** [comment]
Hi,

`LoadStory(String state)` isn't supposed to be used with a path pointing to a resource file. It is only used if you want to load a specific state previously exported with `GetState()`. Maybe this method should be renamed to avoid confusion... 🤔  
If you only want to load your story from a file, I suggest you follow [the instructions in the Readme](https://github.com/paulloz/godot-ink#loading-the-story). Feel free to keep commenting in this issue if said instructions lead to a similar error.

Also, is [this](https://github.com/paulloz/godot-ink/issues/17#issuecomment-619038902) really you demanding a quicker answer like 2 hours after filling this issue? Wow, I'm lacking words to express how I feel about that...

>
>
> Bump

**Comment by shingle-bells** [comment]
Sorry about that.

**Comment by paulloz** [comment]
No worries. Do let me know if anything isn't working as intended/expected.
