### ISSUE TITLE
Having trouble activating in 3.2.1

### ISSUE THREAD

**Issue by cheeds** [paulloz/godot-ink#19]
Hello, I'm really new to this. The trouble shooting mentions adding an ItemGroup to the .csproj file, but I really have no idea where in the file to add the ItemGroup. I still get errors in the places I have tried to put it. Please advise, thank you!

**Comment by paulloz** [comment]
Hi @cheeds, sorry you're having trouble with this. I hope I can make the setup easier in a near future.  

Did you find the `.csproj` file of your game yet? Once you tried building your project once it should be in the root folder near the `project.godot` file. It is an XML file structured like so:
```xml
<?xml version="..." encoding="..."?>
<Project ToolsVersion="..." DefaultTargets="..." xmlns="...">
  <PropertyGroup>
    ...
  </PropertyGroup>
  ...
  <ItemGroup>
    ...
  </ItemGroup>
  ...
  <!-- You can paste the missing ItemGroup here -->
  <Import Project="..." />
</Project>
```
Right? You can copy the `<ItemGroup>` from the README. pretty much anywhere as a direct child of the `<Project>` tag. I'd advise you to paste it where I wrote the comment in the example above so everything is nice and tidy.  
Once this is done you'll need to go back in Godot, in the **Mono** tab, and click on **Build Project**.  
![image](https://user-images.githubusercontent.com/437025/81747356-41592800-94a8-11ea-99b3-a7fba695291c.png)
There shouldn't be any error anymore (unless there is some from your own code) and you then should be able to activate the add-on.  

Please tell me if anything still goes wrong.

**Comment by cheeds** [comment]
Hello! Thanks for the help. So I updated my .NET Framework, which was part of the issue. Next was figuring our how to open and edit the .csproj file properly, which i referenced this post for: https://stackoverflow.com/questions/5129090/how-to-edit-csproj-file
After that I was able to insert the ItemGroup as instructed. 

Now I have the issue of namespace errors: 
![WhatsApp Image 2020-05-13 at 09 58 27](https://user-images.githubusercontent.com/47249468/81762912-6d07fc80-9500-11ea-940c-b4239d80a204.jpeg)
![WhatsApp Image 2020-05-13 at 09 58 00](https://user-images.githubusercontent.com/47249468/81762917-6f6a5680-9500-11ea-87ca-974ecc59b5ff.jpeg)

I tried adding "using Ink.Runtime;" but it didn't work. Is there a specific version of ink I should have downloaded? Currently, I've only got the ink in the form of the inky editor. Should I be using inklecate or some other version?

**Comment by cheeds** [comment]
Ahh! I missed the very important line, _"The last thing you'll need to do in order to get going is to put **ink-engine-runtime.dll** at the root of your Godot project."_  I couldn't find the ink-engine-runtime.dll in the ink docs, but I found it after searching in my **Inky installation folder.**  It all works now, Thank you so much for your time!

**Comment by paulloz** [comment]
Aaaah, yes. I do not provide the actual ink package, that way everybody can use the version they want. You can indeed find it inside your Inky application or directly on the [ink repo](https://github.com/inkle/ink/releases).  

Glad you got it working. I'll see how I can make the documentation and installation process more understandable when I have time :slightly_smiling_face:
