### ISSUE TITLE
Unable to activate plugin

### ISSUE THREAD

**Issue by shrnjad** [paulloz/godot-ink#2]
![Screenshot 2019-04-18 at 18 31 27](https://user-images.githubusercontent.com/2298493/56376536-68431d00-6208-11e9-82bb-670d26735365.png)

Just by downloading the latest commit and adding it to an empty Godot project, I get the error message that the plugin does not compile. When I open the file in the editor I do not see anything suspicious.

My Godot version is v3.1.stable.mono.official.

Any ideas?

**Comment by paulloz** [comment]
Hi, can you have a look at your `.csproj` file and tell me if `PaullozDotInk.cs` and `Story.cs` are listed for compilation?

**Comment by shrnjad** [comment]
Yes, I added the ItemGroup from the Troubleshooting section to the `.csproj` file and Visual Studio Code does not show me any compile errors.

I am still not able to activate the plugin with the same error message. But I will try to create a Singleton Story node like you write in the description. If that works out, I don't have to activate the plugin. ;)

**Comment by shrnjad** [comment]
Ok, so I just added the Story script to a node and could get the first line out of an Ink JSON without activating the Plugin.

It is exactly what I want. Thank you Paul, I will close the Issue now.

**Comment by paulloz** [comment]
@shrnjad glad to hear that, I'll try to make an update so the plugin is easier to use. Feel free to open issues if you have any other difficulty.
