### ISSUE TITLE
.json files not showing new text in dock, and .ink files cannot be loaded in 3.2.1

### ISSUE THREAD

**Issue by cheeds** [paulloz/godot-ink#20]
Hello, just thought I'd point out this potential bug, and look for some solutions. 

Here's a test .json, after clicking one choice, the next options do not show up.
![image](https://user-images.githubusercontent.com/47249468/81837284-3c16de80-9577-11ea-90c4-afb833d341b2.png)
my script also does not load the texts after the choices, even after calling .ChooseChoiceIndex and .Continue.

Further, the .ink version has loading errors when loading via the import dock or the Ink Story node: 
![image](https://user-images.githubusercontent.com/47249468/81837733-ceb77d80-9577-11ea-8f0a-94aac7bbabf2.png)

please advise, I'm not sure I'm missing something obvious! Thank you

**Comment by paulloz** [comment]
This is indeed a bug. Although, one more thing you'll probably need to configure is the path to inklecate (in your project settings, inside the new ink section) if you want to compile `.ink` files directly.  
I'm working on a fix right now.

**Comment by paulloz** [comment]
Hi @cheeds, I made a quick fix for this issue so you can have a functional addon to play with.  
You should be able to import `.json` (and `.ink` as long as the setting is set as stated in my previous comment) without much trouble.  
Be sure to re-import your resources (it should be automatic but who knows at this point 🙁)
The following error message is still here but shouldn't prevent anything from working:
```
Cannot erase nonexistent section "params".
```

---

Please do not close the issue as it is not fully resolved yet.

**Comment by cheeds** [comment]
Hi! just to clarify, how do  I set the path to inklecate? And by inklecate do you refer to the inklecate.exe? Do I simply copy the path to it from the file explorer? Thank you so much!

**Comment by cheeds** [comment]
Hello! Just wanted to say that it seems to be working fine now, with both .ink and .json files. The params error still pops up but that's ok for now. However, it seems like doing things in a very specific order will lead to things falling apart again. So I had to reset everything with my mono version of godot, generate a new .cproj file, then set everything up according to your readme and this post: https://www.reddit.com/r/godot/comments/e8bjn9/dialogue_and_branching_choices/

Thought I would link and mention this in case more beginners need help with this!

**Comment by paulloz** [comment]
I'm glad you seem to have everything working. Do you still need answers for your [question about inklecate](https://github.com/paulloz/godot-ink/issues/20#issuecomment-628637629)? I'll try to add that as well to the documentation anyway.  

I'm curious about what was falling apart and why you had to reset your mono environment tho.

**Comment by cheeds** [comment]
I think I got the path to inklecate working right! my .ink file is autoloading each time I update it. 

I'm not sure why either. I loaded your latest commit, and then tried to load a .json to the story dock. It managed to print all the choice outcomes, then i switched to a .ink and it didn't work, switched back to the .json and that stopped working too. I added the inklecate path after doing this, but it didn't fix anything.  I think it might have to do with setting up the inklecate path from the beginning in project settings, and making sure to re-import the ink files once a change has been made.

**Comment by paulloz** [comment]
Weird. Although, the dock thingy was really quickly made and isn't really robust. It may have been broken by loading a malformed `.ink` resource, I'll try that tomorrow. That being said, if the dock is broken it doesn't mean the entire addon is. I'd love to find time to really get into Godot's UI system and make a more decent debug dock at one time.
