### ISSUE TITLE
Can't Get Variable?

### ISSUE THREAD

**Issue by lunarcloud** [paulloz/godot-ink#24]
They're null when GetVariable and nothing happens when I observe.

I tried moving the variables to the main instead of included ink, I tried using json vs ink in the "Ink Story" node. Nothing.

**Comment by lunarcloud** [comment]
I also tried adding something like: 

````
	public object GetVariableState()
	{
		return this.story.variablesState;
	}
````

but that also printed null. And it seemed silly, but worth trying anything

**Comment by paulloz** [comment]
Can you give me specifics? Versions of Godot, of Ink, etc.

**Comment by lunarcloud** [comment]
OK, so I added logging in the observer section of InkStory.cs

````
this.observer = (String varName, object varValue) => {
			Godot.GD.Print("Emit ", varName, " = ", varValue);
			if (this.observedVariables.Contains(varName))
				this.EmitSignal(this.ObservedVariableSignalName(varName), varName, this.marshallVariableValue(varValue));
		};
````

And it seems like varValue is good, but when it gets to the gdscript side

````
ink.connect(ink.ObserveVariable("Setting"), self, "_update_setting")
...
func _update_setting(name, value):
	print(name, " = ", value)
````

it messes up and becomes null.

Godot 3.2.2.stable.mono.official
Inklecate 9.0 ( https://github.com/ephread/inkgd/releases/tag/0.2.0 )
Latest Release of this plugin ( https://github.com/paulloz/godot-ink/releases/tag/v0.5 )

**Comment by paulloz** [comment]
What's supposed to be in the variable please?

**Comment by lunarcloud** [comment]
I've tried numeric, string, and list values - no difference

**Comment by paulloz** [comment]
Lists won't work for sure. I've tried strings and numerics just now (both from C# dans GDScript) without any issue 🤔

**Comment by lunarcloud** [comment]
Hold on... ugh... it wasn't recompiling my ink for subsequent testing.
string, boolean, numeric all work.

I first tested with a list value.
Didn't realize you have to re-import everytime you want it to recompile the ink.
