### ISSUE TITLE
MacOS Godot Will Not Allow Add-on to be Enabled  

### ISSUE THREAD

**Issue by yetanotheruniqueusername** [paulloz/godot-ink#25]
Godot v 3.2.2
MacOS v 10.15.7

Copied godot-ink into the add-on folder of a blank, new project. 
Shows up in Project -> Project Setting -> Plugins. 
When I click Enable box, I get the following pop-up:
"Warning! 
Unable to load addon script from path: 'res://addons/paulloz.ink/PaullozDotInk.cs'."

Just for the hell of it:
Opening the import_ink.gd in Godot works just fine, it opens it in the script editor.
Trying to open InkDoc.tscn I get the following pop-up:
"Error loading: InkDock.tscn
Load failed due to missing dependencies:
res://addons/paullozink.ink/InkDock.cs
res://addon/paullozink.ink/InkStory.cs"

I can choose Fix Dependencies to find the .cs files, but they only show up in the file browser when I switch from "All Recognized" to "All Files." 

Even after Fixing Dependencies and Opening the Scene anyway, I still am unable to enable the add-on as described above.

**Comment by paulloz** [comment]
Hello! Sorry for the delay, I was in vacation.  

- Are you using a mono version of Godot? https://godotengine.org/download/
- Have you tried [those](https://github.com/paulloz/godot-ink#theres-an-error-or-godot-crashes-when-i-enable-the-plugin) troubleshooting steps?
  - Drop the `paulloz.ink` folder into your `addons/` folder.
  - Modify the `.csproj` file as suggested.
  - Build your project once (from the **Mono** tab).
  - Enable the plugin.

**Comment by yetanotheruniqueusername** [comment]
No worries on the wait. Looking at a lot of solutions to various problems right now. Very early in the project phase. 

I was not using the mono version! So, one would think that would solve the problem. 

However, after using the proper version, I still couldn't get the add-on to turn on. I got the following error: 
"Unable to load addon script from path: 'res://addons/paulloz.ink/PaullozDotInk.cs' There seems to be an error in the code, please check the syntax."

So, I tried turning on Mono to do the rebuild, as you suggested. I get the following error:
"The type or namespace name 'Ink' couldn't be found (are you missing a using directive or an assembly reference?" This comes up twice. 

I do have the ink-engine-runtime.dll in the root of the project file. 

I didn't think it would help, but I copied your ItemGroup suggestion and put it in the .csproj file and instead I got a really long error message about duplicate items. So, I assume it did not want those references as it could find them just find on its own.

Sorry if these are fairly low level questions/problems, I am relatively new to coding.

**Comment by paulloz** [comment]
Don't worry, there's no wrong questions.
I think the `.csproj` management changed in 3.2.2 and I haven't updated the README yet. Could you try to do the same thing you did adding the ItemGroup but using this one instead?
```xml
<ItemGroup>
    <Reference Include="Ink">
        <HintPath>$(ProjectDir)/ink-engine-runtime.dll</HintPath>
        <Private>False</Private>
    </Reference>
</ItemGroup>
```

If you still have build errors with this, would you mind copy/pasting both the error and your `.csproj` file?

Bests.

**Comment by yetanotheruniqueusername** [comment]
We are making progress! I using that ItemGroup I was able to get the add-on to be turned on after building out again in the Mono tab. 

However, now Godot is having difficulty importing .ink files. 

So, for testing purposes I've just been using TheIntercept.ink from Inkle. 

I import it and get the error "editor/editor_file_system.cpp:1801 - Error importing 'res://TheIntercept.ink'."

So, I go to Reimport it under the Import tab as you described in the documentation. When I click on TheIntercept.Ink, it immediately wants to Import As an ink file, no need for me to even pick something from the drop down menu. But then when I click Reimport, I get the same error: " editor/editor_file_system.cpp:1801 - Error importing 'res://TheIntercept.ink'."

Turning off the Compress button seems to have no effect, same error message. 

However, a new file, TheIntercept.ink.import, does appear in the same folder as TheIntercept.ink. 

If I do try to load TheIntercept.Ink in the Ink tab, I get the following three errors:

 Failed loading resource: res://TheIntercept.ink. Make sure resources have been imported by opening the project in the editor at least once.
 Error loading resource: 'res://TheIntercept.ink'.
 The story you're trying to load is not valid.

But I assume that's because I cannot get Godot to properly import the .ink file.

**Comment by paulloz** [comment]
If your issue is only with ink compilation (understand: loading json files is working), then you probably didn't configure the compiler.  
From the [README](https://github.com/paulloz/godot-ink#how-to-use):
> If you want to directly compile your `.ink` files, you'll also need to download the [ink compiler](https://github.com/inkle/ink/releases) on your computer and copy/paste the path to `inklecate.exe` into your project settings _(Project -> Project Settings... -> Ink -> Inklecate Path)_.

**Comment by yetanotheruniqueusername** [comment]
Sorry, should have mentioned that I already did add inklecate to Project Settings under Ink. It originally only looked for .exe files, but after I switched it to All Files, I was able to select the Mac version. Occasionally this error will pop-up and I wonder if that's related: 

 editor/import/editor_import_plugin.cpp:123 - Condition "!(get_script_instance() && get_script_instance()->has_method("get_option_visibility"))" is true. Returned: true

So, for now, compiling the Ink files in Godot may be out for me. 

Anyway! JSON files DO work when I used a sample one I just made. Using the old intercept files didn't work, I would get error messages that the file was made with too old of a copy of ink. I tried then, to use a more recently made Ink file from the same project and it still didn't work, still getting 

 editor/editor_file_system.cpp:1801 - Error importing 'res://test.ink'

Even after trying to reimport with the path to inklecate in the Project settings thing. Is this perhaps a MacOS problem since the plug-in seems to want an .exe file?

So, for now I can make the JSON files work and should be able to employ the plug-in. Thank you for the exhausting walk through on that. It is not a huge deal to just export all ink files as JSON if that's the route the project ends up going. Appreciate you making this plug-in!

**Comment by paulloz** [comment]
I unfortunately don't have any MacOS compatible hardware to check this but on Linux I still point to the `.exe` file as I feed it to mono anyways ([here](https://github.com/paulloz/godot-ink/blob/master/addons/paulloz.ink/import_ink.gd#L46-L47)).  

I leave this open, maybe someone else using MacOS will enlighten us.

**Comment by ephread** [comment]
> I leave this open, maybe someone else using MacOS will enlighten us.

I believe it's happening because the official prebuilt binary for macOS already packages a mono runtime. Running it through [mono a second time](https://github.com/paulloz/godot-ink/blob/master/addons/paulloz.ink/import_ink.gd#L50) is likely to fail. A possible workaround might be to use the linux / windows `.exe` version, until a more permanent solution can be found.

**Comment by francoisdlt** [comment]
Hello !
I'm having the same issue on macOS when loading` .ink` file instead of `.json `:  `The story you're trying to load is not valid.`
I've tried setting `inklecate` to the macOS binary, as well as to the Windows binary, with no success in either case.

Compiling to JSON first works as expected. 

My configuration : 

- Godot 3.2.3 mono stable official
- macOS 11.2

**Comment by paulloz** [comment]
Hello there. Yeah, I'm aware there are some issues with how I execute inklecate on MacOS. However, as I don't have any access to Apple hardware at the moment, I'm afraid I won't be able to personally test what's going on nor do anything more than trying to fix this blindly.  
Currently, MacOS is handled with [the same code](https://github.com/paulloz/godot-ink/blob/master/addons/paulloz.ink/import_ink.gd#L49-L50) as Linux/BSD. The issue probably comes from here and fiddling with both how the `.exe` is called and how we feed him arguments should do the trick somehow.

**Comment by francoisdlt** [comment]
I've been fiddling around following your indications, and I think I have found the problem. 

The importing error finds its origin in a `127` return code from the `OS.execute` mono call. This was weird because running the same command manually yielded the expected result (return code 0 and file parsed correctly)

Looking for help over the Internet (https://godotforums.org/discussion/24788/execute-bash-script-from-gdscript-using-os-execute), I came to suspect that the OS.execute was not resolving the mono symbolic link (actually a chain of several symbolic links). Under my system, this is how the mono executable is referenced : 

`mono ⇒ /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono ⇒ /Library/Frameworks/Mono.framework/Commands/mono ⇒ mono-sgen ⇒ mono-sgen64 `

By feeding the actual executable mono path to the `OS.execute`, the import runs fine. 

Should this be considered a bug of `OS.execute` ?

**Comment by francoisdlt** [comment]
Oh boy how dumb I've been....
Since there **IS** a macOS inklecate binary, we don't actually NEED mono to run the import 🤦 
Putting the macOS inklecate binary in the settings + popping the mono from the command line (same behavior as Windows entry) works perflectly !

so my code looks like this : 

 ```
       match OS.get_name():
            "OSX":
                arguments.pop_front()
                var _err = OS.execute(inklecate, arguments, true)
            "X11":
                var _err = OS.execute("mono", arguments, true)
            "Windows":
                arguments.pop_front()
                var _err = OS.execute(inklecate, arguments, true)
            _:
                return null
```

To make things perfectly clean, a couple of bolts to tighten : 
- the ".exe" filter on the inklecate path needs to be adapted when running on macOS (or removed at all ?)
- maybe turn the logic around on this whole "popping mono out of the command line" ? and have it popped in only for linux ?

If you want I can open a PR for this ?

**Comment by paulloz** [comment]
Hey :)

> * the ".exe" filter on the inklecate path needs to be adapted when running on macOS (or removed at all ?)
> * maybe turn the logic around on this whole "popping mono out of the command line" ? and have it popped in only for linux ?

Sure, seems like good ideas.

> * add a little documentation / tooltips for helping the users use the adequate inklecate

Sadly, Godot's API doesn't expose anything to add tooltip in project setting's at the moment ☹️ 

> If you want I can open a PR for this ?

Go for it 🙂

**Comment by francoisdlt** [comment]
May someone test this under Linux ?

**Comment by paulloz** [comment]
Yeah I'll check a couple of Linux/BSD platforms ^^

**Comment by paulloz** [comment]
This should now be fixed on **master**. The patch will be packaged with the next version (**v0.8**).

**Comment by BenjaminLawson** [comment]
It looks like this fix was accidentally reverted in https://github.com/paulloz/godot-ink/commit/74262a832391ae64d552af7bb68a21af267864e6#diff-d758259d0de804251d8fb3f449ca82249b8435a7d88046293482d67fdce70a0dL49-R52

**Comment by paulloz** [comment]
@BenjaminLawson Good catch, that was an absolutely failed merge of another commit 🤦   
Thanks! It should be alright after edc26ea.
