### ISSUE TITLE
Should we be using master or .5 tag?

### ISSUE THREAD

**Issue by jimpodroskey** [paulloz/godot-ink#27]
Hi! Trying with master, when I create my addons folder and try to load the plugin I get:

Unable to load addon script from path: 'res://addons/paulloz.ink/PaullozDotInk.cs'.

The file exists.

Any insight on next steps for troubleshooting?

**Comment by paulloz** [comment]
Hi,

You probably haven't built the C# project before trying to load the plugin? I'll make sure to write that more explicitly in the README.

**Comment by drandell** [comment]
@jimpodroskey I'm using the latest master code and have it working. My .csproj had some extra items (i cant remember why), i cleaned it up a little and its all working for me now. 
Might be worth posting yours just in-case.

@paulloz I think the readme needs some work. For example, you mention the .dll but not where to get it. I initially compiled it from source until i realized it was with the compiler. 
Another question for you regarding inklecate.exe, the setting, does that require the path or does it require the path and the filename? i.e. `D:\inklecate` or `D:\inklecate\inklecate.exe`

(also as an ease of life issue, is it not possible to have a window dialog to select the path or exe instead of having to copy and paste it in?) 

Awesome job on the addon btw, going to try it out properly soon :)

**Comment by paulloz** [comment]
>
> My .csproj had some extra items (i cant remember why)
>

Because you need to reference the runtime `.dll` (manually or via nugget).

>
> (also as an ease of life issue, is it not possible to have a window dialog to select the path or exe instead of having to copy and paste it in?)
> 

It already is. 
![image](https://user-images.githubusercontent.com/437025/103578205-73efdf00-4ed6-11eb-97bd-1e3a7f4697bc.png)

**Comment by drandell** [comment]
@paulloz i don't see that;
![image](https://user-images.githubusercontent.com/393945/103578771-160bc900-4ecf-11eb-9673-b18a97e4fcfb.png)

And regarding my project file, no it was this;
```
<Project Sdk="Godot.NET.Sdk/3.2.3">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Tools</Configuration>
    <LangVersion>8.0</LangVersion>
    <ProjectGuid>{DB00ED65-226D-4856-AE9B-6DB9D971D0B8}</ProjectGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>Project</RootNamespace>
    <AssemblyName>Project</AssemblyName>
    <CodeAnalysisRuleSet>roslynator.ruleset</CodeAnalysisRuleSet>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <TargetFramework>net472</TargetFramework>
    <!--The following properties were overriden during migration to prevent errors.
    Enabling them may require other manual changes to the project and its files.-->
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="Ink">
      <HintPath>$(ProjectDir)/ink-engine-runtime.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference> 
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Roslynator.Analyzers">
      <Version>3.0.0</Version>
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Reactive.Linq" Version="4.4.1" />
    <PackageReference Include="Unity.Container" Version="5.11.8" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2"/>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="scripts\**\*.cs" />
  </ItemGroup>
</Project>
```

**Comment by drandell** [comment]
Must be a little godot bug @paulloz , i disabled the plugin and re-enabled and the folder icon appeared.

**Comment by paulloz** [comment]
@jimpodroskey do you have an update regarding this issue? Based on the answers here and the updated README?

**Comment by paulloz** [comment]
Without any news on this and as it seems to be user error, I'm closing.
