### ISSUE TITLE
Loading Ink Story

### ISSUE THREAD

**Issue by drandell** [paulloz/godot-ink#29]
Hi @paulloz ,

The documentation isn't quite clear on this and I would like to think i'm doing this correctly. 
I have my ink story loaded into Godot, but i am not seeing any of the exported variables?

The docs mention this;
```
To load your story, you can:

Point the InkFile exported variable to your .json/.ink file and check the AutoLoadStory checkbox in the inspector.
Point the InkFile exported variable to your .json/.ink file (in the inspector or via a script) and call story.LoadStory().
```

But all i see in the inspector for my Ink file is below;
![image](https://user-images.githubusercontent.com/393945/104778519-614a9500-5775-11eb-8af0-798eaaa50e6b.png)

Any clarification as to what i am doing wrong would be appreciated :)! 

For reference;
Using Godot_c#_v3.2.3

**Comment by paulloz** [comment]
As written just above the point you quoted:
> Everything is handled in an InkStory node.

![image](https://user-images.githubusercontent.com/437025/104779887-2b5ede00-5780-11eb-838d-5e22b9b67569.png)
1. Need to add a node to the scene (or this could be done in an autoload/singleton or whatever seems right for your architecture). 
1. The exported property you're looking for is here.

**Comment by drandell** [comment]
Thanks for the clarification @paulloz ! 
I've done as you've said and noticed something odd, 
![image](https://user-images.githubusercontent.com/393945/104823047-2b71e300-583f-11eb-902a-117072575664.png)

Autoload story is selected, and just doing that alone doesnt seem to be loading the Ink Story in;
![image](https://user-images.githubusercontent.com/393945/104823084-5c521800-583f-11eb-85cc-55bab184cec9.png)

Calling the LoadStory then works, so i always have to call LoadStory? (The docs dont seem to imply that).

**Comment by paulloz** [comment]
The load is triggered in `_Ready`. Your code here is triggered in `_EnterTree` which is called before that.

**Comment by drandell** [comment]
Thanks for the help @paulloz
