### ISSUE TITLE
How to Clone plugin

### ISSUE THREAD

**Issue by Caligari** [paulloz/godot-ink#3]
So, I'd love to use this in a subtree, in a project, but the plugin includes the full addons tree, which means it needs to be added at the root of the project, which hasn't been something my git-fu has allowed me to do?

In the end I've cloned it to a separate directory and made a git out of the paulloz.ink directory, which I grab into my other project.

Is there a reason you have included the root of the tree?

**Comment by paulloz** [comment]
Hi @Caligari, this folder structure is needed to be able to distribute on the [Godot Asset Library](https://godotengine.org/asset-library/asset) in the future. You can see it is the same as [other plugins](https://github.com/paulloz/godot-colorblindness).  
For now the process for mono plugins is a bit weird so this plugin is not release on the Asset Library but I hope for it to be in a near future.  
For now what you're doing seems just fine, is that too much of an inconvenience?

**Comment by Caligari** [comment]
I'm very new to Godot. Making this so it is ready for inclusion in the library makes perfect sense!
