### ISSUE TITLE
Why the dll must place in root directory?

### ISSUE THREAD

**Issue by AmyF** [paulloz/godot-ink#32]
**Describe the bug**

I want to move the dll to `addons` to keep project clean, but plugin don't work.
I try to put the dll in `addons/paulloz.ink` or other directory. (and i make the dll path and csproj onsistent.)
there are no errors and warnings, but i can't call "Load a file" in Ink board.

**To Reproduce**

1. drop the `paulloz.ink/` folder in my project's` addons/` folder
2. drop `ink-engine-runtime.dll` and `ink_compiler.dll` in  `addons/paulloz.ink`
3. modify the csproj: write two dll's path to csproj
4. open the project
5. click `Ink` in the bottom bar
6. click `Load a file` button

`Load a file` button does not respond.

**Environment**
* OS: Windows 10
* Godot version: 3.2.3-mono 
* godot-ink version: 0.7
* ink version: 0.9.0

**Additional context**
forgive me, it doesn't look like a bug. but I don't know where to ask this question.

**Comment by paulloz** [comment]
Hey.  

This is not a bug but has to do with [how the runtime locates assemblies](https://docs.microsoft.com/fr-fr/dotnet/framework/deployment/how-the-runtime-locates-assemblies).  
If you do not want to clutter your project root folder, you have several options:
* put `ink-engine-runtime.dll` under a directory the prober is going to check, e.g. `$(ProjectDir)/ink-engine-runtime/`
* use `<Private>true</Private>` so `ink-engine-runtime.dll` is copied in `$(ProjectDir)/.mono/temp/bin/$(Configuration)/`

Btw, as it is used exclusively for `.ink` files compilation, you don't have to put anything in your `.csproj` file regarding `ink_compiler.dll`. The only requirement is for it to be in the same folder as `inklecate.exe`.

**Comment by AmyF** [comment]
you are really a kind person. hope your library can bring happiness to more people and the wolrd.
thank you, @paulloz .
