### ISSUE TITLE
Support for Multiple .INK files in 1 Project

### ISSUE THREAD

**Issue by CypherHyenaSoftware** [paulloz/godot-ink#34]
**Describe the bug**
If you have multiple .INK Files that reference each other with diverts, some will fail to Import properly because they are seen as Invalid INK files because the divert targets are in another file. The MAIN .INK file compiles because it has the sub-files INCLUDED, but the sub-files don't work unless they also INCLUDE all related files to them.

**To Reproduce**
Create an INK file called Locations.ink and an INK file called Characters.ink and an Ink file called Main.ink. Have Main include the other 2. Add Diverts from Locations to Characters and from Characters to Locations. Godot will likely fail on import on 1 or more of these - but it depends on which order they are imported.

**Environment**
* OS: Windows 10 64b
* Godot version: 3.2.3 Mono
* godot-ink version: latest as of 3/14/21
* ink version: Unknown? Latest Inklecate downloaded as of 3/5/21

**Additional context**
A related note is that if you make a change in a Subfile that is INCLUDED in your main file, it doesn't recompile the story until the MAIN file is updated.

**Comment by paulloz** [comment]
Part of this issue is fixed by 35a2adb.  
However, subfiles don't trigger a recompilation when they change for now. I've opened a proposal (godotengine/godot-proposals#2477) to be able to make this happen somewhat cleanly.
