### ISSUE TITLE
BindExternalFunction in GDScript fails (regression from 0.7)

### ISSUE THREAD

**Issue by francoisdlt** [paulloz/godot-ink#37]
**Describe the bug**
Calling `BindExternalFunction` in GDScript works in version 0.7, but fails in version 0.8 with the following error message : 
```
variant_to_mono_object: Attempted to convert Variant to an unmarshallable managed type. Name: 'Func`1' Encoding: 21.
  <Erreur C++>  Method failed. Returning: __null
  <Source C++>  modules/mono/mono_gd/gd_mono_marshal.cpp:690 @ variant_to_mono_object()
```

**To Reproduce**
`story.BindExternalFunction("<ink_func_name>",self,"<godot_func_name>")`

**Environment**
* OS:  macOS
* Godot version: 3.3
* godot-ink version: 0.8
* ink version: 0.9

**Additional context**
I'm using GDScript and I'm not sure I'm using the correct syntax for the BindExternalFunction ...

**Comment by paulloz** [comment]
Indeed, that's a regression. Thanks for the report.

**Comment by francoisdlt** [comment]
if I use directly `story.BindExternalFunction("<ink_func_name>",self,"<godot_func_name>",bool)` (with the lookahead param at the end) I don't have the error anymore .......

**Comment by paulloz** [comment]
Yeah I know; that's caused by 357bc7c5804fe9926bd394494af274dd362f8647. I just didn't have any time to fix this yet.
