### ISSUE TITLE
[Godot 4] C# readonly properties inaccessible from GDScript

### ISSUE THREAD

**Issue by rambda** [paulloz/godot-ink#43]
**Describe the bug**

Due to https://github.com/godotengine/godot/issues/67167, cannot access any readonly properties of C# instances from GDScript, e.g. `InkStory.CurrentText`.

**To Reproduce**

```
@tool
extends EditorScript

# Called when the script is executed (using File -> Run in Script Editor).
func _run() -> void:
	var s := load("res://Examples/TeenyTiny/Assets/Example.ink")
	print(s.get_property_list())
	print(s.CurrentText)
```

**Environment**
* OS: 
* Godot version: 4.beta.17-mono
* godot-ink version: 
* ink version: 

**Additional context**

Apparently it's not godot-ink's fault. I just want to inform GDScript people of this issue. If godotengine/godot#67304 gets merged, this will be fixed.

**Comment by paulloz** [comment]
Yep, that’s why as a temporary workaround there are fallback methods for r-o properties. E.g. for `CurrentText`: https://github.com/paulloz/godot-ink/blob/godot-v4/addons/GodotInk/Src/InkStory.Interop.cs#L33

**Comment by rambda** [comment]
> Yep, that’s why as a temporary workaround there are fallback methods for r-o properties. E.g. for `CurrentText`: https://github.com/paulloz/godot-ink/blob/godot-v4/addons/GodotInk/Src/InkStory.Interop.cs#L33
> 
> I’ll make sure to document it when writing the documentation.

Well, I didn't know this class exists and what's `partial` keyword for until now (not familiar with C#). Thanks.

**Comment by paulloz** [comment]
Thanks for the report, still!

**Comment by paulloz** [comment]
I added a new page about GDScript interop on the [wiki](https://github.com/paulloz/godot-ink/wiki/Interop-With-GDScript) 😉
