### ISSUE TITLE
Link the documentation on the AssetLib page and in the asset itself

### ISSUE THREAD

**Issue by greenfox1505** [paulloz/godot-ink#52]
You shouldn't be expected to download the Asset from the AssetLib, then to find the repo, then go find the wiki, then go figure out how to get your project working.

The package downloaded from the AssetLib should include everything you need to get started, including any `ReadMe.md` for basic use and compiling instructions. Anything more can still be "hey, for more indepth tutorial, go to the wiki linked here!", but Minimum Viable Product, the asset should include instructions.

**Comment by paulloz** [comment]
First of all, hello.

I guess that's fair, I actually never considered the AssetLib as an entry point, given how abysmal its discoverability and UX are. I'll update the AssetLib description to include a link to the [documentation](https://github.com/paulloz/godot-ink/wiki). And I'll have a glance at what kind of documentation other packages provide in their add-on folder. My gut feeling is, for the most part, documentation that's hosted elsewhere on the internet is the norm.

Thanks for the report.

**Comment by greenfox1505** [comment]
Thank you! Even if that documentation is just "please check here(LINK) for the latest documentation", that's a good start.

I think most packages don't actually do a very good job of their AssetLib presence. IMHO, that is a mistake.

My day job is Unity stuff. Unity developers love their plugin store. Godot could be doing a lot better in that aspect.

Thank you for this project. I was looking into write a parser myself before finding your project. I'm currently working on some tooling to make this easier to use from GDScript before kicking off a game jam in a few weeks. If that's something you'd find useful, I'll do a pull request.

**Comment by paulloz** [comment]
> IMHO, that is a mistake.

It's more due to the fact the AssetLib and everything related to it is a PITA. It makes no sense to dedicate actual time to it. Even less so for C# add-ons.

> I'm currently working on some tooling to make this easier to use from GDScript before kicking off a game jam in a few weeks. If that's something you'd find useful, I'll do a pull request.

From here, I'm not sure that it's going to be something I'd plan on adding to this project. The goal is to keep the scope fairly minimal. And adding specific tooling for GDS (apart from mandatory interop code) doesn't *feel* like it'd fall in scope. But feel free to open something with more detail when the time comes, I'll make sure to have a look.

**Comment by paulloz** [comment]
The addon folder now contains a copy of the `README.md` file, which contains basic installation instruction, and links to the wiki.
