### ISSUE TITLE
Repo home page download link broken

### ISSUE THREAD

**Issue by JeFawk** [paulloz/godot-ink#55]
**Describe the bug**

<img width="1005" alt="image" src="https://github.com/paulloz/godot-ink/assets/7268697/43926a47-0d96-4d8e-8518-0e7f5d4e8a74">

This download link is broken.

**To Reproduce**

**Environment**
* OS: 
* Godot version: 
* godot-ink version: 
* ink version: 

**Additional context**

**Comment by paulloz** [comment]
The link was updated.
