### ISSUE TITLE
Missing installation info for mac 

### ISSUE THREAD

**Issue by JeFawk** [paulloz/godot-ink#57]
**Describe the bug**

I'm a bit confused so apologies for my lack of knowledge. On my current Godot 4.1.1 there is no button to create the .csproj file, so I don't think I can follow the installation instructions.
This is the only option I have in the Tools:
<img width="544" alt="image" src="https://github.com/paulloz/godot-ink/assets/7268697/97e4690f-d6bb-49ff-bfaa-e81d701e5b56">

Is there something I'm missing or doing wrong maybe?

**To Reproduce**

**Environment**
* OS: macOS 12.6
* Godot version: 4.1.1

**Additional context**

**Comment by paulloz** [comment]
Hello, 

By the looks of it, I'd say you are not using the .NET version of Godot?
https://godotengine.org/download/macos/
https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html

**Comment by JeFawk** [comment]
> Hello,
> 
> By the looks of it, I'd say you are not using the .NET version of Godot? https://godotengine.org/download/macos/ https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html

Apologies, you are correct, I am using the top one.
Must I install the .NET version for this plugin to work?

<img width="438" alt="image" src="https://github.com/paulloz/godot-ink/assets/7268697/00e5f8ea-3125-4bff-8399-9a10989a5fdc">

**Comment by paulloz** [comment]
Yes, this repository only provides C# code.

**Comment by JeFawk** [comment]
> Yes, this repository only provides C# code.

I understand, my bad, thank you for explaining.

**Comment by paulloz** [comment]
I'll leave this open for now. Feel free to continue here if you're experiencing more difficulties.

**Comment by JeFawk** [comment]
Getting stuck at the runtime part of the guide. After adding the script to the VBoxContainer and building the project again
<img width="941" alt="image" src="https://github.com/paulloz/godot-ink/assets/7268697/106c9802-c75d-4a55-aa45-ddccab9680b2">

Godot starts throwing all these errors:

<img width="1670" alt="image" src="https://github.com/paulloz/godot-ink/assets/7268697/c3a77e09-5588-4c5f-bf5c-84ca7fb62211">

I tried this last night and it was the same thing happening. Today I made a brand new project and started following the steps again, only to run into the same issue.

Any ideas if you'd be so kind?

**Comment by paulloz** [comment]
Not really. This is a common error in Godot 4.1 (see godotengine/godot#78513), but I never personally experienced it while using GodotInk. Nor have I heard of other people experiencing it.

**Comment by JeFawk** [comment]
> Not really. This is a common error in Godot 4.1 (see [godotengine/godot#78513](https://github.com/godotengine/godot/issues/78513)), but I never personally experienced it while using GodotInk. Nor have I heard of other people experiencing it.

Thank you, I'll follow the development of that bug.
The Ink preview worked, so I guess after that bug is fixed I can run the plugin :) thanks for the help!!

**Comment by hunterloftis** [comment]
With this version of Godot, I consistently hit the unloading assemblies bug with godot ink:

Godot v4.3.stable.mono - Fedora Linux 40 (Workstation Edition) - Wayland - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i7-1280P (20 Threads)
