### ISSUE TITLE
Error with InkDock.tscn

### ISSUE THREAD

**Issue by HVukman** [paulloz/godot-ink#60]
**Describe the bug**
No InkDoc Tab appears on the bottom. Error: scene/resources/packed_scene.cpp:92 - Condition "nc == 0" is true. Returning: nullptr

**To Reproduce**
Installing Addon on Godot 4. Trying to open InkDock.Tscn

**Environment**

Godot 4.1.1. Stable Mono, Windows
* godot-ink version: 1.0

**Comment by HVukman** [comment]
I donwloaded the code from the Repo. I can enable it in the editor. There was no other error during installation.

**Comment by paulloz** [comment]
Closing, for lack of update.
