### ISSUE TITLE
Installation process should not force you to have a csproj file

### ISSUE THREAD

**Issue by DomDumont** [paulloz/godot-ink#61]
Hi,
I am very interested by your project but i do not use the c# version of godot.
I do not have the option to create a csproj ( there is nothing in project/tools).
It would be nice if you can make a version that does not force users to have the c# version of godot.
Thanks a lot for your work !

**Comment by paulloz** [comment]
Hello, this add-on (and ink at large) is written in C#. A *"version that does not force users to have the C# version of Godot"* would be a vastly different thing, and would need to be based on a third party ink runtime. [One](https://github.com/ephread/inkgd) was entirely re-written in GDS. [Another](https://github.com/brwarner/inkcpp) possibility is a C++ rewrite that could be used through [GDExtension](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/what_is_gdextension.html). In any case, this is not the intent behind this repository. GodotInk is intended to simply be an integration of the official (C#) ink runtime.  

On Godot's side, there's a plan for the editor version to be unified (i.e. there won't be a dedicated C# version any more). But, even then, using GodotInk will bring the same dependencies in as it does currently.

**Comment by DomDumont** [comment]
Hello,
Thanks for the rapid answer. I did not know. My idea was that a plugin was "only" a dll and its usage does not depend on the langage it was written with ...  But i understand now and it's perfectly clear that it's a totally different project. 
Thanks again to bring your project to the community.

**Comment by paulloz** [comment]
"Only a .dll" doesn't mean much without context. A native .dll and one containing a managed assembly wouldn't be treated in the same way at all.
