### ISSUE TITLE
Errors after rebuilding the game during installation on Godot 4.1.1

### ISSUE THREAD

**Issue by darth-biomech** [paulloz/godot-ink#66]
I've got the latest copy of the code from the repo, moved "addons" folder from the zip into my project's folder, made edit to .csproj file, exported project once like it says in the installation guide (deleted .godot folder before that and restarted the editor after for a good measure), and upon trying to activate the plugin, I get the following error:
`res://addons/GodotInk/plugin.gd:10 - Parse Error: Invalid cast. Cannot convert from "res://addons/GodotInk/Src/InkStoryImporter.cs" to "EditorImportPlugin".`

**Comment by paulloz** [comment]
> exported project once like it says in the installation guide

The guide doesn’t say to export the game, only to build it (as in: click the build button in the top-right corner of Godot). If you still have issues after that, can you make sure it builds without issue? And join the detailed build logs to this issue?

**Comment by paulloz** [comment]
Closing, for lack of update.
