### ISSUE TITLE
Included Ink files doesn't cause the Ink Story to be recompiled correctly

### ISSUE THREAD

**Issue by klootas** [paulloz/godot-ink#68]
**Describe the bug**
Changing the content of an Ink file that is included in an Ink story does not cause the story to be recompiled correctly the next time the game is executed.

**To Reproduce**
Here's a repro of the problem:
https://github.com/klootas/GodotRepro.git

1. Open repro project in the Godot editor
2. Run the project using F5 and notice that the first Ink choice is called "Choice A1"
3. Open Ink/Test.ink (a file that is "included" by Ink/Story.ink), in an external editor
4. Change the first choice text to "Choice A2"
5. Switch back to the Godot editor
6. Press F5 and notice that the running game still says "Choice A1" (instead of the expected "Choice A2")

**Environment**
* OS: Windows 11
* Godot version: 4.1.1
* godot-ink version: 1.1.0
* ink version: 1.1

** Additional context **

My ink_cache.json in the user folder:
{"res://Ink/Story.ink":["res://Ink/Test.ink\r"]}

**Comment by paulloz** [comment]
That `\r` is most certainly the issue. It's due to Windows' EOL characters. I'll make a patch for that as soon as I have time.

**Comment by klootas** [comment]
You're right, this fixes it:

File: InkStoryImporter.cs:105

Current:
.Select(match => sourceFile.GetBaseDir().PathJoin(match.Groups["Path"].Value))

New:
.Select(match => sourceFile.GetBaseDir().PathJoin(match.Groups["Path"].Value.Trim()))

Good call 👍
