### ISSUE TITLE
Update quickstart guide with platform info

### ISSUE THREAD

**Issue by kaisoapbox** [paulloz/godot-ink#76]
Thanks for this repo, I was thinking of exploring using Godot and Ink together and was very relieved to discover someone else already did the heavy lifting of making an integration! Happy to report that `godot-ink` seems to work on the latest Godot version `4.2.0-rc.1` (at least, so far...)

That being said, I had a small bit of trouble getting set up on a fresh installation (some C# issue about the `Ink` namespace not being recognized) which I realized was due to the Ink compiler not being set up properly during the build process. It turned out to be because the Ink zip downloaded during the pre-build process is hard-coded in `GodotInk.props` to be `inklecate_windows.zip`, but I'm on a Mac machine!

I managed to solve my issue with the fix laid out below, and I suggest that the wiki be updated to include this as step 2 (or as a note).

1. Update the following line in the `addons/GodotInk/GodotInk.props` file (below
    the `<!-- File -->` comment):
    ```xml
    <InkZip>inklecate_PLATFORM.zip</InkZip>
    ```
    Replace PLATFORM with your OS platform (i.e. `windows`, `mac`, or `linux`).

I tried making a PR to update the wiki directly, but apparently that's not something GitHub supports.

Also worth noting, a fuller way of solving this problem is to write something to detect platform and download the correct zip accordingly, but that sounds much messier; I'm not familiar enough with Godot to know how to set that up, unfortunately.
(and sorry for submitting this as a "bug", for some reason GitHub Issues isn't letting me submit a normal issue?!)

**Comment by paulloz** [comment]
Hi 👋  
The zip we download shouldn't be an issue. It's platform specific because it also contains the compiler as a binary, but we don't use it. We only use the .dll (and they're not platform specific).  
I don't have an OSX machine to test, but there's probably another issue. I know several persons who use GodotInk without issue on OSX. If you can, I'd be interested in more details about what the exact error is, and a binlog of the failing compilation (you can activate binlogs in Godot: editor settings, dotnet, build, create bin log).

**Comment by kaisoapbox** [comment]
Huh, I created a new project, set the `.csproj` back to `inklecate_windows.zip`, and everything works normally. I can't seem to straightforwardly reproduce the error I first encountered. Not sure what happened there then, since my change did seem to resolve my issue the first time round, but I'll close this issue since it's not clear what's going on. Sorry about that!

**Comment by paulloz** [comment]
Fair enough ✌️  
Feel free to re-open if you encounter this again and/or understand what was going wrong.
