### ISSUE TITLE
InkStory isn't a GlobalClass when using Godot 4.2

### ISSUE THREAD

**Issue by valknight** [paulloz/godot-ink#79]
**Describe the bug**

When using Godot 4.2, `InkStory` is not a `[GlobalClass]`, breaking various bits of functionality.

**To Reproduce**

1. Open a new project in Godot 4.2 .NET
2. Add `godot-ink` and build solution
3. Add a GDScript, with the following contents
```gdscript
extends Node

@export
var story: InkStory
```
4. Notice that `InkStory` isn't found in the current scope

**Environment**
* OS: macOS Sonoma 14.1
* Godot version: 4.2.0 - .NET
* godot-ink version: 1.1.1
* ink version: 1.1.1 (love that this is the same right now <3)

**Additional context**
This seems to be caused by `GODOT4_1_1_OR_GREATER` not being true in Godot 4.2. Changing `InkStory.cs` to be as follows fixes this issue:

```csharp
#if GODOT4_1_OR_GREATER
[GlobalClass, Icon("../GodotInk.svg")]
#endif
```

This shouldn't be a breaking change, as Godot 4.1.0 also comes with support for `[GlobalClass]`. I'm happy to make a PR if this looks all fine, but, I just wanted to flag this before doing so, to ensure this isn't already known, and, another solution isn't being worked on.

**Comment by paulloz** [comment]
Hello! Thank you for the report.

I noticed this last week thanks to a [forum post](https://forum.godotengine.org/t/cross-language-c-class-typing-in-gdscript-with-godot-4/35959/3?u=paulloz). I thought I wrote an issue for it, but I apparently forgot. It is indeed simply a typo with the extra `_1`. I'll find some time to push an update here, and on the asset library ❤️

**Comment by valknight** [comment]
No worries! If it helps, I've just put a PR in with the fix 😄 ✨
