### ISSUE TITLE
Unable to export release builds due to missing assembly reference

### ISSUE THREAD

**Issue by VishalRamki** [paulloz/godot-ink#81]
**Describe the bug**
The game builds and runs perfectly fine. However, when I attempt to export the game using Godot's export window, the game always fails with the following error.

```
CS0234: The type or namespace name 'Parsed' does not exist in the namespace 'Ink' (are you missing an assembly reference?) PATH_TO\GodotProject\main.cs(6,11)
 ```

**To Reproduce**
I build the project, and then attempt to export it. Thats it.

**Environment**
* OS: Windows 10 LTSC 21H2 Build 19044.3803
* Godot version: 4.2.1.mono
* godot-ink version: 1.1.1
* ink version: 1.1.1

**Additional context**
I hid my drive path.
The ink version comes from the .godot/mono/ink-v1.1.1

Thank you for taking the time to review this issue. I apologize in advance if I have forgotten to include anything.

**Comment by paulloz** [comment]
Hello, can you show the content of your `main.cs` file?

**Comment by VishalRamki** [comment]
The following is my complete `main.cs` file. Thank you for your assistance.

```csharp
using Godot;
using System;
using GodotInk;
using System.Runtime.CompilerServices;
using System.Text;
using Ink.Parsed;
using System.Collections;
using System.Collections.Generic;

public partial class main : VBoxContainer
{
	[Export]
	private InkStory story;
	
	[Export]	
	private Label story_label;

	[Export]
	private VBoxContainer menu_container;


	public override void _Ready()
	{
		story_label = GetNode<Label>("ScrollContainer/Story");
		menu_container = GetNode<VBoxContainer>("StoryOptions");
		ContinueStory();
	}
	
	private void ContinueStory()
	{
		foreach (Node child in menu_container.GetChildren())
			child.QueueFree();
			
		#region Insert new Break lines to for better readability
		string story_content = story.ContinueMaximally();
		StringBuilder content = new StringBuilder(story_content);

		int start = 0;
		List<int> breaklines = new List<int>();
		while (story_content.Find("\n", start) > 0) {
			var n = story_content.Find("\n", start);
			breaklines.Add(n);
			start = n+1;
		}

		int[] computedBreakLines = breaklines.ToArray();

		for (int i = 0; i < computedBreakLines.Length; i++) {
			content.Insert(i + computedBreakLines[i], "\n");
		}

		story_label.Text = content.ToString();

		#endregion

		foreach (InkChoice choice in story.CurrentChoices)
		{
			Button button = new() { Text = choice.Text };
			button.Pressed += delegate
			{
				story.ChooseChoiceIndex(choice.Index);
				ContinueStory();
			};
			menu_container.AddChild(button);
		}
	}
}
```

**Comment by paulloz** [comment]
You are importing `Ink.Parsed` yourself. It is a namespace only defined in the compiler, and should not be used for runtime. This is not an addon issue.

**Comment by VishalRamki** [comment]
After removing that reference, it exports without issue. I am not sure when or why I chose to import `Ink.Parsed`. I use VSCode for my C# editing, so I don't know if that did the import or not. I should have paid more attention to the imports.

I apologize for the issue. 

Thank you very much for you time and thank you for your work on this addon.

**Comment by paulloz** [comment]
No worries, do not hesitate if you have other issues 🙏
