### ISSUE TITLE
i can not find the .csproj file in my godot4.2

### ISSUE THREAD

**Issue by nemeseven** [paulloz/godot-ink#82]
<img width="263" alt="image" src="https://github.com/paulloz/godot-ink/assets/145114494/18964975-d8c1-4364-900c-e7eafc36f4c3">

**Comment by paulloz** [comment]
Hello. I'm not sure what the reported issue is, here. Your `.csproj` file won't be listed in Godot's filesystem dock, since it's only listing resources. The file should have been created by the engine whenever you created your first C# script, or you can ask for its creation from the *Project, Tools* menu.

**Comment by nemeseven** [comment]
> Hello. I'm not sure what the reported issue is, here. Your `.csproj` file won't be listed in Godot's filesystem dock, since it's only listing resources. The file should have been created by the engine whenever you created your first C# script, or you can ask for its creation from the *Project, Tools* menu.

sorry about my question，i mean that i can not build project，when i created c#⃣️ solution。

**Comment by paulloz** [comment]
I'm unsure about how I can help. What does "cannot build project" mean here? Are there errors? Did you go through the installation steps described in the [wiki](https://github.com/paulloz/godot-ink/wiki#%EF%B8%8F-installation)?

**Comment by nemeseven** [comment]
<img width="911" alt="image" src="https://github.com/paulloz/godot-ink/assets/145114494/0b78731f-f186-4ede-8b95-2a79c820b9ef">
i finished the step3 of your wiki,but i do not know how to do step 2 and 3. My GotInk plugin always unable.

**Comment by paulloz** [comment]
You can't have finished the third step without doing the second. Do you have a `.csproj` file in your project's root folder? If not, go to Godot and click *Project, Tools, C#, Create C# Solution*. It'll create the file. After that, edit it like described in step 2, and go forward from there.

**Comment by nemeseven** [comment]
yes，i follow your instruction go step3 firstly，but when i created C# solution，there is not .csproj file in my project's root folder. It is so wired.

**Comment by paulloz** [comment]
I'm sorry, I really can't help you if you don't provide more information.

**Comment by nemeseven** [comment]
<img width="804" alt="image" src="https://github.com/paulloz/godot-ink/assets/145114494/1051b426-6964-4654-b1f1-2c15c5c5a08c">

I find my csproj file,and finished the step2 like the image i uploaded.Is it that right?

**Comment by paulloz** [comment]
This is not your (nor a) `.csproj` file. Look at the window's title, it says `GodotInk.props`.

**Comment by paulloz** [comment]
This looks like a network issue preventing the dependency from being downloaded. Some possibilities:
- this was intermittent, and works now
- you're being some kind of firewall that blocks the download from `github.com`
- wherever you are in the world forbids access to `github.com`

**Comment by paulloz** [comment]
Closing, for lack of update.
