### ISSUE TITLE
ink doesn't load in export

### ISSUE THREAD

**Issue by lunarcloud** [paulloz/godot-ink#9]
When I go to export my project, it no longer runs.

It does load the ink if you place it relative to the same location as it would be in the project structure.

**Comment by lunarcloud** [comment]
Oop, I'm still new to Godot.
I figured it out, it's an export setting thing.

http://docs.godotengine.org/en/latest/getting_started/workflow/export/exporting_projects.html?highlight=export#export-mode 

Maybe reference this in your Troubleshooting section?

**Comment by paulloz** [comment]
Thanks, I added a [line about exports](https://github.com/paulloz/godot-ink#game-export) in the `README`.
