### ISSUE TITLE
Can't find the Story property in the inspector

### ISSUE THREAD

**Issue by GJKiseki** [paulloz/godot-ink#91]
Hi, Paul! I have a question.

I have successfully enabled the plugin and now I'm proceeding to the step **The runtime** on the wiki. After I defined the InkStory class and clicked the Build button, I didn't find the **Story** property in the root node. I'm so confused about what step I might have missed...

![image](https://github.com/paulloz/godot-ink/assets/118507424/5cae489d-9774-46ca-8b57-1c2b5a07a1fa)

I'm really new to this. Please advise, and thank you so much for your help and patience!

My Environment:
Windows 11
.NET 8.0 SDK
Godot 4.2.2
godot-ink v1.1.2

**Comment by paulloz** [comment]
It seems your `QuickStartGuide` class is defined in a file named `ink.cs`. But the class you use with Godot need to be defined in files sharing the same name[^1]. If you try launching your project, you'll probably see an error in relation to that.  
I suggest having a look at some of the introduction pages of the Godot documentation, like [your first game](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/index.html), and [C# basics](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html).

[^1]: https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#example

**Comment by GJKiseki** [comment]
It works! Thanks for your help and your suggestion! 

I was surprised to find that Godot doc supports Chinese too! As you can see, I have never learned about coding. This can be my first step into the coding world, thanks again! 😄

**Comment by GJKiseki** [comment]
Resolved!
