### ISSUE TITLE
Godot complaining icon GodotInk.svg not found

### ISSUE THREAD

**Issue by Phoenixkaze** [paulloz/godot-ink#95]
**Describe the bug**

Godot keeps complaining icon GodotInk.svg not found.

![image](https://github.com/user-attachments/assets/e64b6f80-9305-4408-8fae-d4308f7e05ec)

godot-ink has been placed to the suggested location i.e. `res://addons/GodotInk`

Source unmodified.

Somehow Godot is trying to access the icon at `res://GodotInk.svg`

Changing the icon path to absolute path `res://addons/GodotInk/GodotInk.svg` works

**To Reproduce**

**Environment**
* OS: Windows
* Godot version: 4.3 stable mono
* godot-ink version: 1.1.2

**Comment by paulloz** [comment]
Hello, and thank you for the report. This is an issue in the current stable 4.3 of Godot. It has already been fixed. See godotengine/godot#95592 for details.
