### ISSUE TITLE
Continue() not working as expected when calling external functions

### ISSUE THREAD

**Issue by knochenhans** [paulloz/godot-ink#97]
**Describe the bug**
Continue() should get new content _per line_, but this doesn't seem to be true when calling external functions in a script like so:
```
EXTERNAL test(text)

-> Main
=== Main ===
~test("1")
~test("2")

-> DONE
```
Calling Continue one time produces the following output:
```
1
2
```
The desired output for only a single call is:
```
1
```

**To Reproduce**
Set up the above script, bind an external function, and run Continue a single time:

```Csharp
[Export]
public InkStory InkStory { get; set; }

public override void _Ready()
{
  InkStory.BindExternalFunction("test", new Callable(this, MethodName.TestFunction));
  
  InkStory.Continue();
}

public void TestFunction(string text)
{
  GD.Print(text);
} 
```

I’ve upload a minimal example here: [inktest.zip](https://github.com/user-attachments/files/17382661/inktest.zip)

**Environment**
* OS: Arch Linux (Kernel Version: 6.10.10-arch1-1)
* Godot version: v4.3.stable.mono.arch_linux
* godot-ink version: 1.1.2

**Comment by paulloz** [comment]
Hello!

`InkStory.Continue()` only forwards the call to the internal `Continue()` method on ink's side. You are right to say it should only return a single line of content, and it does. But lines beginning with a `~` aren't really considered *content*. For instance, it makes little sense to have it stop in between code lines in the following script, given the goal of the method is to pull the next line of text from the story.
```
~ temp n = RANDOM(1, 100)
~ temp r = n % 2
{ r:
- 0: This is even.
- else: This is odd.
}
```
Hope this makes sense. You can test this by using the official runtime alone, outside a Godot project, for instance.

**Comment by knochenhans** [comment]
Hi, thanks for clearing that up. I just stumbled over [this](https://github.com/inkle/ink/issues/526) thread which pretty much explains it. I guess I’ll just set up a message queue to collect all incoming external function calls on Godot’s side and process them, as a workaround. I’m working on using Ink as a more general purpose scripting system, so keeping external function calls separate and waiting for them to finish is essential.
